### ISSUE TITLE
Note array to Score Part

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#101]
Create a method that transforms note array to part (not sure if necessary to provide time signature). This method can be used on loading score from match files or from MIDIs and called within the `load_score_midi` and `load_match` functions.

**Comment by melkisedeath** [comment]
### A generic function to transform an enriched note_array to part.

The function can be used for many different occasions, i.e. load_score_midi part_from_match, part_from_graph, etc.This function requires a note array that contains time signatures and key signatures(optional - can also estimate it automatically).  

Note array should contain the following fields:
  - onset_div and/or onset_beat
  - duration_div and/or duration_beat
  - pitch
  - ts_beats
  - ts_beat_type
  - step(optional)
  - alter(optional)
  - octave(optional)
  - key_mode(optional)
  - key_fifths(optional)
  - id(required but can also be empty)

Parameters:
-------------
- note_array : structure array or list of structured arrays
- assign_note_ids : bool (optional)
      assigns note_ids
- ensurelist: bool (optional)
      ensures that output part is a list
- estimate_key: bool (optional)


Returns
-------
part : list or Part or PartGroup
    Maybe should return score
