### ISSUE TITLE
Inconsistent default staff values

### ISSUE THREAD

**Issue by nimrodVarga** [CPJKU/partitura#12]
In **io.importmusicxml._handle_direction** the default value for 'staff' is 1 if there is none specified, however for other objects the default value is None.
The 1 should be changed to None, so as to be consistent with the other values and it also makes more sense, what if there is no staff 1 specified anywhere in a score?

**Comment by mgrachten** [comment]
Fixed by PR https://github.com/CPJKU/partitura/pull/23
