### ISSUE TITLE
Partitura merge parts does not create new voices or staff.

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#120]
This is a potential bug. For example, in kern when two columns are parsed then this creates two parts.
Ideally, we would like to merge these parts using `partitura.score.merge_parts()` and assign their _Timed Elements_ to different staffs or voices.

This could be a flag like `reassign_staff` or `reassign_voices` in `merge_parts` but potentially it could be very useful.

**Comment by sildater** [comment]
+1 that would be very useful.
