### ISSUE TITLE
Inconsistent note id renaming.

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#121]
There is an inconsistent renaming in note IDs when PartGroup is parsed vs calling first `pt.score.merge_parts`.
This can cause issues on exporting match files for example. 

PartGroup renames ids : `n01` -> `P00-n01`
`pt.score.merge_parts` : `n01` -> `n01-01`

As an additional issue, one can call a `PartGroup.note_array(unique_id_per_part=False) ` to get `n01` instead of `P00-n01` which fails if it's not called from a `PartGroup` or `PartList`. This is not consistent with the method `part.note_array()` and should be fixed by just being ignored for simple parts.

**Comment by melkisedeath** [comment]
Fixed the second part of the issue for consistent argument forwarding.
