### ISSUE TITLE
Examples for methods in `partitura.musicanalysis`

### ISSUE THREAD

**Issue by neosatrapahereje** [CPJKU/partitura#13]
It would be important to add examples in the documentation to all methods in `partitura.musicanalysis` module. This would make the usage of these methods clearer to the users without having to dive into the code.

Methods with missing examples:

* `estimate_spelling` (in `partitura.musicanalysis.pitch_spelling`)
* `estimate_key` (in `partitura.musicanalysis.key_identification`)
* `estimate_voices` (in `partitura.musicanalysis.voice_separation`)
* `estimate_tonaltension`(in `partitura.musicanalysis.tonaltension`)

**Comment by mgrachten** [comment]
I merged my local commits into `develop`, which add an example for `estimate_key` to `docs/usages.rst`, in a section `music analysis`.  This section can be extended with example calls for the other functions.

**Comment by neosatrapahereje** [comment]
Commit 7b13650 adds the examples in the documentation, and are now included in pull request #26
