### ISSUE TITLE
Add example in the documentation for loading MIDI files

### ISSUE THREAD

**Issue by neosatrapahereje** [CPJKU/partitura#14]
Partitura has two methods for loading MIDI files, `load_performance_midi` and `load_score_midi`, which return `PerformedPart` and `Part` objects, respectively. For users that are not familiar with the distinction between score and performance, this might be confusing. Therefore, it would be important to add an example in the documentation of a usual pipeline for getting common information from a MIDI file (e.g., MIDI pitch, MIDI velocity, onset times in seconds, etc.), as well as a quick guide that helps users decide which loading method would be the appropriate for their use cases.

**Comment by mgrachten** [comment]
Ideally, the section should discuss both load methods, and a "quickstart" function `load_midi` (to be written), that uses `load_performance_midi` internally, and returns the `note_array` attribute of the resulting `PerformancePart`. Perhaps this function should be introduced before the other methods. Perhaps a new issue should be created for writing this `load_midi` function.

**Comment by sildater** [comment]
I'll have a look at this `load_midi` function and write an example script with explanations.

**Comment by mgrachten** [comment]
Thanks for moving this forward @sildater. I wonder if the name `midi_to_notearray` or `midifile_to_notearray` (instead of `load_midi`) would help to avoid confusion about the use of this function vs. `load_midi_score` and `load_midi_performance`.

**Comment by mgrachten** [comment]
Anyway, perhaps you could create a PR for this branch once its more or less ready, and tag us for review before merging into `develop`.

**Comment by sildater** [comment]
+1 for a different name! I will definitely get back to you as I'm unsure how to generate the documentation.

**Comment by mgrachten** [comment]
> +1 for a different name! I will definitely get back to you as I'm unsure how to generate the documentation.

in your python environment do:

    pip install sphinx sphinx_rtd_theme

Then (from the repo root dir):

    cd docs
    make html

This should create a folder `_build/html` with the rendered documentation (open `index.html` in your browser to view).

To run/check the code snippets in the documentation run:

    make docs

Note that some code snippets run the `render` function, which requires lilypond or musescore to be installed.
