### ISSUE TITLE
Add support for all MIDI controls in `PerformedPart`

### ISSUE THREAD

**Issue by neosatrapahereje** [CPJKU/partitura#15]
Currently, `PerformedPart` only adds sustain and soft pedal information and discards other MIDI controls. In order to add support for all MIDI controls, they need to be registered in performed part. 

Furthermore, instead of having a dictionary with the name and number of the control types, only register the number of the control messages. This would make `MIDI_CONTROL_TYPES` no longer needed, so it should be removed.

**Comment by mgrachten** [comment]
Fixed by https://github.com/CPJKU/partitura/pull/24
