### ISSUE TITLE
Use Part or PerformedPart objects directly as inputs for methods in `partitura.musicanalysis`

### ISSUE THREAD

**Issue by neosatrapahereje** [CPJKU/partitura#16]
Until now, all methods in `partitura.musicanalysis` take a note array (i.e., a structured array) generated from a `Part` object as an input. Since these methods are also commonly applied to *performance* information, it would be very useful to allow users to also use the methods with information from a `PerformedPart` object. Furthermore, allowing the input to these methods to be either a structured array, a `Part` or `PerformedPart` object would simplify their usage.

**Comment by mgrachten** [comment]
The `ensure_notearray` is now in `develop` and can be imported as `partitura.utils.ensure_notearray`. I propose to call the `note_array` argument to the music analysis functions something like `score`, `score_info`, or `note_info` (or some similar generic name) to reflect the fact that one can pass either a Part, PartGroup, or note_array.

**Comment by neosatrapahereje** [comment]
+1 to use `note_info` as the argument name instead of  `note_array`!  

I just updated the methods for key and pitch estimation (in branch `update_api_musicanalysis` in commits 
0297fc5 and 285f067 respectively), but as a result, the import score MIDI is currently broken. I will  not merge this branch into `develop` until I fix the MIDI import.

**Comment by neosatrapahereje** [comment]
Importing score MIDI works again!

**Comment by neosatrapahereje** [comment]
@mgrachten Better late than never! This issue is finally solved for all methods in `musicanalysis` in branch `update_api_musicanalysis` (with commit e14dae6).
