### ISSUE TITLE
Restructure time-related fields in the `note_array` property of `Part` and `PerformedPart` objects

### ISSUE THREAD

**Issue by neosatrapahereje** [CPJKU/partitura#17]
In order to avoid confusion with different time units (e.g., beats, quarters, divs for `Part` objects), it would be beneficial to rename the time-related fields in note arrays to be explicit about the units:

* Structured note arrays should include all available time units (e.g., `onset_beats`, `onset_quarters`, etc.).
* Remove redundant properties (i.e., remove `note_array_quarters`), as well as deprecate the `note_to_notearray` method (in `partitura.utils.music`).
* Check compatibility with new field names throughout package, specifically:
  * the `note_array` attribute of the `PartGroup` class
  * the `musicxml_to_notearray` function

**Comment by sildater** [comment]
I added new note_array properties for both Part and PerformedPart. load_performance_midi used a flag to switch between quarters and seconds, I modified it such that it stores both in the note, cc, and pc dictionaries. In this way, we don't have to recover one from the other at generation of the note_array (not straightforward if there are tempo changes). However, "sound_off" ("note_off" with pedal offset) in the note_array is currently only supported for divs (aka ticks aka quarters * ppq). Might be confusing behavior if the notes have different lengths in different units in the note_array. What do you think?

**Comment by mgrachten** [comment]
Ok, so in the note_array `duration_div` would include pedal and `duration_sec` would not? That's a definite no-go I think. They should be either both with or both without. Since with the structured_array we have relative freedom to include fields as we see fit, I wonder whether we could just add fields `duration_sustain_divs` and `duration_sustain_sec`. (or without sustain, if they default duration fields include sustain).

**Comment by mgrachten** [comment]
minor issue about the field names: we have `divs` plural, and `sec` singular. Perhaps we can choose plural or singular for both.

**Comment by mgrachten** [comment]
also, don't forget to remove the existing `notearray` attribute.

**Comment by sildater** [comment]
+1 on extra field for sustain adjusted note_off. The naming is singular div in the note_array field.

**Comment by mgrachten** [comment]
Oops, you are right, I was writing from the top of my head. sorry
