### ISSUE TITLE
overlapping functionality in musicanalysis.performance_codec and utils.music

### ISSUE THREAD

**Issue by sildater** [CPJKU/partitura#202]
The functions ```get_time_maps_from_alignment``` and ```get_matched_notes``` of utils.music do very similar things as ```to_matched_score``` and other functions in musicanalysis.performance_codec. ```musicanalysis.performance_codec.monotonize_times``` seems to be non-functional and/or wrongly documented. 

A bit of refactoring and cleanup in the areas of alignment and performance_codec would be great!

**Comment by manoskary** [comment]
Maybe break the file in music into more files for organizational purposes. Have to carefully verify for circular imports.

**Comment by sildater** [comment]
more comments: `note_features` and `performance_codec` seem sowhat misplaced in `music_analysis`, maybe we should have them in utils as they are basically feature extractors.
