### ISSUE TITLE
Same Note Features may have different feature length depending on the score.

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#205]
When calling `partitura.musicanalysis.make_note_features(part, "all")` this can result in a matrix of different sizes since the features that are not found are skipped. This is problematic for ML workflows and it should be standardized.

Furthermore, the current `make_note_features` only works on partitura `Part` or `PartGroup` but does not work on `Score`.

**Comment by sildater** [comment]
To me this isn't a bug but intended behavior. I could see the use for a flag like "force_features" or "include_empty_features" though to make it possible to get the same number of columns in all feature arrays from different scores.

**Comment by manoskary** [comment]
Yes, I was thinking exactly something like that. Maybe a flag `pad_empty` or `include_empty_features` would work.
