### ISSUE TITLE
bug in load_musicxml

### ISSUE THREAD

**Issue by anusfoil** [CPJKU/partitura#206]
The `load_musicxml` function can only unzip the `.mxl` file when the zipped `.xml` file has the same name as the `.mxl` file. This works fine for more standardized musicxml data from ASAP and Vienna 4x22, but for a lot of public scores sourced from musescore community it's not the case. Often after unzip we find the contained score named `score.xml` and in this case will generate error. 

```
with zipfile.ZipFile(filename) as zipped_xml:
    xml = zipped_xml.open(
        os.path.splitext(os.path.basename(filename))[0] + '.xml'
    )
```
The following snippet is a simple fix:
```
with zipfile.ZipFile(filename) as zipped_xml:
    contained_xml_name = zipped_xml.namelist()[-1]
    xml = zipped_xml.open(
        contained_xml_name
    )
```

**Comment by sildater** [comment]
Good catch! The fix looks good too, you can directly open a PR to the develop branch.
