### ISSUE TITLE
Brahms Hungarian Dance No 5 xml breaks grace note feature generation

### ISSUE THREAD

**Issue by sildater** [CPJKU/partitura#212]
Minimal example: 
```
score = pt.load_musicxml(path)
feats = pt.make_note_features(score, "all")
```
The most likely cause are note IDs set to None as the problem disappears if note IDs are forced at score loading.
[Brahms_Hungarian-Dance-5_Full.zip](https://github.com/CPJKU/partitura/files/10959539/Brahms_Hungarian-Dance-5_Full.zip)

**Comment by manoskary** [comment]
It could only raise a warning to the user if note ids are missing when loading the score or trying to compute the note features. Still to debate for next release.
