### ISSUE TITLE
Different length of pianorolls from partitura and pretty_midi

### ISSUE THREAD

**Issue by thomas3913** [CPJKU/partitura#219]
I create pianoroll representations from MIDI-files with partitura with the following parameters:
remove_silence=False,piano_range=True,time_div=100,time_unit="sec"

And I create pianorolls with the pretty_midi module using the following code:
file = pretty_midi.PrettyMIDI(entry)
pr = file.get_piano_roll(fs=100)

I expected the pianorolls to have the same length, but the length differs by large factors.

[pianoroll_problem.zip](https://github.com/CPJKU/partitura/files/11110923/pianoroll_problem.zip)

**Comment by manoskary** [comment]
Hello, 

thank you for sharing this issue! 
Please provide a complete working code snippet and some of the problematic files.

**Comment by thomas3913** [comment]
Hello,

I have added a zip folder with a python code snippet and some exemplary MIDI files from different datasets, but I had the problem with any MIDI file. I also included a screenshot of the output. There you can see that the size of the second dimension of the shape is not the same using the two methods. (I do not mean the 88 and 128 which is because of piano_range==True)

**Comment by manoskary** [comment]
Hello, the issue with the different sizes is caused by the silence at the end of the file. Partitura displays all notes until the end of the last note, however, pretty midi in this case displays some additional frames of silence.

**Comment by manoskary** [comment]
It will be fixed on Next release 1.2.3

**Comment by manoskary** [comment]
## Update 

This issue is being addressed with PR #320
