### ISSUE TITLE
Performance features

### ISSUE THREAD

**Issue by anusfoil** [CPJKU/partitura#230]
Incorporate the performance expression attributes in musicanalysis module. 

Asynchrony
- asynchrony amount and correlation 

Dynamics
- Agreement and consistency 

Articulation
- Overlap ratio between adjacent notes, in staccato & legato setting

Tempo:
- explore the tempo smoothing methods 
- wavelet and relationship with tempo markings

Phrasing

**Comment by sildater** [comment]
I'll add some points here:
- performance_features should be completely independent of note_features. 
- for all information that is both in the full note feature array and in the full performance feature array (mainly score onset and duration as well as pitch) there need to different field names to enable array joining without errors: currently that's not the case for all duplicate note features as well as pitch
- make a list and documentation of general purpose low-level performance features that make sense in partitura.
