### ISSUE TITLE
Render score/notes in a Python GUI

### ISSUE THREAD

**Issue by Lelant** [CPJKU/partitura#250]
Hello,

I would like to ask a general question. My goal is to write a Python Application with a GUI to display and interact with the notes in a score. So I want to be able to click the notes and show the properties for example. Is this possible with Partitura?

The render() function only seems to open the score in MuseScore or Lilypond or writing to a file. But I would like to display the notes in a GUI, so the user can interact with the notes. Is there any way this is possible? What could be a first approach to this problem?

Thank you very much, any help or suggestion is appreciated.
Best wishes, Tim

**Comment by Lelant** [comment]
I'm sorry. I don't know how to put the label "question" on this issue.

**Comment by manoskary** [comment]
Hello Tim, 

thank you for your question.
Unfortunately, such a functionality does not exist in partitura as GUI is not the focus of the package.
You can of course preview all properties of all objects on the timeline but there is no link to the objects and their corresponding position on a SVG render.
However, there is a tool that can do what you asked for mei scores:
[Here is the link.](https://mei-friend.mdw.ac.at/)
