### ISSUE TITLE
Partitura does not support Python <= 3.6

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#259]
```shell
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
python-BaseException
```

Linked googled [response](https://github.com/csuhan/ReDet/issues/14)

**Comment by sildater** [comment]
we could just bump the requirements to 3.7 ?

**Comment by neosatrapahereje** [comment]
I agree. I think that 3.9 has a good level of adoption already, so moving to 3.7 shouldn't be that much of an issue.
