### ISSUE TITLE
match file version 1.0.0 voice parsing bug

### ISSUE THREAD

**Issue by sildater** [CPJKU/partitura#267]
in the newest match file version voice information is stored as scoreattribute number with a prefix "v". this is not correctly parsed in load_match, where the voice information is cast to integers. The loading doesn't break but all voice information is lost.

**Comment by sildater** [comment]
I'll add it here: the match files for chopin excerpts in 4x22 contain note IDs without dashes, e.g., "n1", the others contain repeats and are identified with dashes, e.g., "n1-1". It would probably be good to have this consistent and append a suffix for the ones without repeats.

**Comment by manoskary** [comment]
Is this linked issue to any PR? Should it be scheduled for Release 1.3.2 ?

**Comment by sildater** [comment]
@huispaty are you looking into this for the next release? 

some more things I just checked:
- voice information as part of the ScoreAttributesList is not documented in the match specification: https://cpjku.github.io/matchfile/
- I think the problem stems from `number_pattern = re.compile(r"\d+")` and 
```
            note_attributes["voice"] = next(
                (int(a) for a in note.ScoreAttributesList if number_pattern.match(a)),
                None,
            )
```
in `importmatch.py`
- I'm not sure whether this regex for voice number is used anywhere else 
- I'm not sure whether earlier match files encoded voice information beyond the "s" tag.
- my other comment about consistency in 4x22 might be moot because of the unfolding required foir Schubert and Mozart, just ignore it
