### ISSUE TITLE
automatic blackening of code might be broken

### ISSUE THREAD

**Issue by sildater** [CPJKU/partitura#269]
release 1.3.0 does not seem to be blackened. e.g. the note_features.py module has very wide lines and horizontal lists.

**Comment by sildater** [comment]
and also doc string length seems to be unaffected by blacken, so we need to check this manually.

**Comment by sildater** [comment]
Ah, yes that's a good idea!

**Comment by manoskary** [comment]
The blacken now works on `develop` and submits a new commit with the blacken code which gains authorship from the person pushing to develop. I will leave this issue open if there are any other remarks about the blacken process, otherwise feel free to close the issue.
