### ISSUE TITLE
Assertion Error for computing performance features when tempo curve < 0

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#275]
Hello, I got an `AssertionError` in the Zeilinger/Magallof subset which occurs when an element of the tempo curve is less than zero.
Reference on line 479 of `performance_codec.py`:
```python
assert((tempo_curve >= 0).all())
```

**Comment by anusfoil** [comment]
Which piece is this? I put the assertion there since tempo should not be negative, if the note order is correct.

**Comment by manoskary** [comment]
> Which piece is this? I put the assertion there since tempo should not be negative, if the note order is correct.

Many pieces actually:
 - match_mag/chopin_op37_No1.match
 - match_mag/match_mag/chopin_op32_No1.match
 
 to name a few.

**Comment by manoskary** [comment]
I think the best course of action would be to replace the assertion with a warning.

**Comment by sildater** [comment]
For the first file the error stems from a `nan` in the tempo curve. This is there because the variable `unique_s_onsets` is not unique but contains twice the same value in the very end.

**Comment by sildater** [comment]
Don't close this yet, I want to dig a bit deeper.
