### ISSUE TITLE
Trill notes are not parsed as such from match v0

### ISSUE THREAD

**Issue by sildater** [CPJKU/partitura#286]
In the example file `pianodata\match\beethoven_op002_no2_mv1.match` there are some trill markings. They do not show up in the alignment and in fact are probably not parsed correctly in line 199 of `importmatch.py`. A reason for the bug could be the regex for the line as defined in line 867 of `matchlines_v0.py`:
```
ornament_pattern: re.Pattern = re.compile(r"trill\((?P<Anchor>[^\)]*)\)-")
```
I think this is missing some regex for the performed note after the dash.

**Comment by huispaty** [comment]
Do you have a testfile for this version? (The one in the [repo](https://gitlab.cp.jku.at/CP/pianodata/-/blob/master/match/beethoven_op002_no2_mv1.match) is of version 5.0)

**Comment by sildater** [comment]
confusingly, v5.0 in match is v0 in partitura (v0 = v0.n.0 for n in 1-5), v1 is only used for v1.0.0

**Comment by manoskary** [comment]
Is this linked issue to any PR? Should it be scheduled for Release 1.3.2 ?

**Comment by huispaty** [comment]
No, it's neither linked to any existing PR nor scheduled for Release 1.3.2 (same for issue [#267](https://github.com/CPJKU/partitura/issues/267)). Both will be handled in the next release.
