### ISSUE TITLE
Upper/lower case note names

### ISSUE THREAD

**Issue by mgrachten** [CPJKU/partitura#30]
The documentation of `Note` suggests that lower case note names can be used for the `step` argument, but this yields unexpected results (calling `render` shows the note at the wrong staff position). The documentation should be updated to use upper case names, and perhaps we should convert `step` to uppercase, for more robustness.

**Comment by neosatrapahereje** [comment]
Fixed with commit d891ae2. The note names in the documentation are in upper case and the `step` of `Note` attribute is converted to upper case.
