### ISSUE TITLE
Running tests locally without miditok

### ISSUE THREAD

**Issue by neosatrapahereje** [CPJKU/partitura#337]
The new tokenizer functionalities require miditok and miditoolbox, which are not yet part of the requirements. Nevertheless, these packages are still used in `test_utils.py`, and result in an error when performing unittests locally.

**Comment by manoskary** [comment]
Hello, I commented on the relevant PR #338 . This should be the intended behaviour. The online tests should run with no problem and check that all external dependencies work. Locally you would expect tests failing when you don't have a dependency with a message dependency X is missing.
