### ISSUE TITLE
Make a Tempo Value Default for Export Midi

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#340]
Midi export should have a default value for Tempo if the tempo is not available or not specified on the score then, for completeness, when it is imported in a DAW, I propose 120bpm. However, this addition is not strictly necessary.

**Comment by sildater** [comment]
I think there is a default for performance export (it's 120 bpm or 500000 mpq). for score export, we have 
```
for tp in part.iter_all(score.Tempo):
            tempos[to_ppq(tp.start.t)] = MetaMessage(
                "set_tempo", tempo=tp.microseconds_per_quarter
            )
```
is this what we need to extend by a default value?

**Comment by manoskary** [comment]
I think so, then when there are no tempo values in iter_all then set to 120bpm.
