### ISSUE TITLE
wrong values in metrical strength features

### ISSUE THREAD

**Issue by sildater** [CPJKU/partitura#363]
the metrical strength features in `note_features.py` return four attributes:
```
"beat_phase",
"metrical_strength_downbeat",
"metrical_strength_secondary",
"metrical_strength_weak"
```
`metrical_strength_downbeat` and `metrical_strength_weak` return 1.0 in the presence of a downbeat which seems wrong for the latter, line 1066 is probably the problem. A bit of documentation on each feature is also missing (what is secondary, what is weak, does it work for triple meters?).

**Comment by manoskary** [comment]
Hello, thanks for the issue. These features are taken from the basis functions of the basis mixer. Some documentation that could always be useful, I can look into it. But maybe @neosatrapahereje would be the best person to write the documentation for that or review the resulting PR.

**Comment by sildater** [comment]
I could also fix, I already know where it is.
