### ISSUE TITLE
Offsets for tied notes incorrect?

### ISSUE THREAD

**Issue by gg-g** [CPJKU/partitura#365]
Python version 3.12.4
Partitura version 1.5.0

onset_div and onset_quarter for tied notes are reported seemingly incorrect

When loading the kern file ([test3.krn.txt](https://github.com/user-attachments/files/16457764/test3.krn.txt))  for following test fragment

![Screenshot from 2024-08-01 16-04-11](https://github.com/user-attachments/assets/8f755ed1-ffc5-4f65-94cd-fa02389eea74)

and generating a note_array

```
import partitura as pt
import pandas as pd

score = pt.load_kern('test3.krn')

note_array = score.note_array(include_pitch_spelling=True, include_metrical_position=True)

pd.DataFrame(note_array)
```

this results in

![Screenshot from 2024-08-01 16-10-18](https://github.com/user-attachments/assets/8a35ee78-cc68-4fae-8480-f019649265cb)

Although there are 4 notes which (should) start at onset_div 0, only two do so, the ones being without a tie.

**Comment by manoskary** [comment]
Hello, 

Thank you for signaling this bug. It will be addressed ASAP. You can hopefully use the fixed version as soon as next week by installing **Partitura** through the develop branch.

To do this:
```shell
pip install git+https://github.com/CPJKU/partitura.git@develop
```
