### ISSUE TITLE
Nakamura-file format functions incorrectly assume that values are tab separated

### ISSUE THREAD

**Issue by mgrachten** [CPJKU/partitura#37]
Since Nakamura does not seem to specify a separation character for the text file formats, I think the functions should accept any whitespace separated data, or at least spaces, as he uses in his examples.

To illustrate the problem: when copy-pasting the data from the example in [Nakamura's manual](https://midialignment.github.io/MANUAL.pdf), page 5:
```
0 1.00833 C#5 73 36 0 0 C#5 73 50
1 1.025 A3 57 32 2 0.00625 A3 57 31
```
The function `load_nakamuracorresp` returns empty arrays.

**Comment by mgrachten** [comment]
I guess `np.loadtxt` with a structured `dtype` argument is a good way to go here:

Given the file 'tst.txt' with the contents:

```
0 1.00833 C#5
1 1.025 A3
```
the call:
```python
np.loadtxt('tst.txt', dtype={'names': ('a', 'b', 'c'), 'formats': ('i', 'f', 'U5')})
```
returns:
```python
array([(0, 1.00833, 'C'), (1, 1.025  , 'A3')],
      dtype=[('a', '<i4'), ('b', '<f4'), ('c', '<U5')])

```
This also works for tab-separated values.

**Comment by neosatrapahereje** [comment]
Fixed in branch `test_nakamura` (see new version of the loaders introduced in commit 8c8fd0e)
