### ISSUE TITLE
Missing UnpitchedNote class

### ISSUE THREAD

**Issue by nimrodVarga** [CPJKU/partitura#4]
As far as I understand correctly, there is no such class and during XML import, all notes without a pitch are treated as Rests, even percussive notes.

I have seen in the documentation of GenericNote that this is planned anyway, I just thought opening an issue might be a good idea.

**Comment by mgrachten** [comment]
Yes, the absence of UnpitchedNote is not by design. Feel free to add it and create a PR against develop.
