### ISSUE TITLE
Merge Parts results to Part with None note types 

### ISSUE THREAD

**Issue by melkisedeath** [CPJKU/partitura#59]
### On partitura/develop

The error occured on Ravel Mirroirs 3_Une_Barque from the ASAP dataset:
```sh
nd = np.array([(n.start.t, n.end_tied.t) for n in part.notes_tied])
AttributeError: 'NoneType' object has no attribute 't'
```
The concerned Piece:
 #[https://github.com/CPJKU/asap-dataset/tree/master/Ravel/Miroirs/3_Une_Barque](https://github.com/CPJKU/asap-dataset/tree/master/Ravel/Miroirs/3_Une_Barque)

The part function was called with :
```python
part = partitura.load_musicxml(fn)
part = partitura.score.merge_parts(part)
```

**Comment by sildater** [comment]
I had a look at this and it seems like there are some issues with the file:
- two a G# grace notes are not properly tied to the previous grace note and the subsequent main note (line 30571, 28139)
- some notes contain two conflicting time-modification tags (e.g. 48908)
- even with this fixed musescore still crashes?

fixing the first issue in the dataset (maybe with slur, I don't think tied grace noes make much sense) fixes the import error.
