### ISSUE TITLE
Cashed properties for time maps in `Part` objects

### ISSUE THREAD

**Issue by neosatrapahereje** [CPJKU/partitura#80]
For many use cases, `Part` objects do not change after being created. Nevertheless, attributes such as `beat_map` and `quarter_map` are being computed every time, which can be very slow for large pieces. Therefore, it would be useful to just compute these properties once.

**Comment by sildater** [comment]
That is true. I tend to use the workaround of assigning the map to a variable ```beatmap = part.beat_map``` and reusing this variable. If the maps are cached we'd need to make sure they're always up to date when adding or removing TimedObjects to or from a part which might be a bit messy.
