### ISSUE TITLE
Inconsistent use of warning and logging

### ISSUE THREAD

**Issue by sildater** [CPJKU/partitura#85]
It seems some functions of partitura use a logger while others use the warnings library. Is there a reason for this or should we fix this? 

Related to this: sometimes it'd be nice if partitura could handle everything silently. Consistent logging/warning makes this easier.

**Comment by melkisedeath** [comment]
I agree that we should correct this inconsistency.l, unless there is a reason to it. I vote for changing completely to warnings that way a script warnings can be silenced easily by doing `python  -W ignore script.py` .
